"""
SmartDB Registry MCP Server (API-backed)
==========================================
Connects to the SmartDB API server over HTTPS instead of direct MySQL.
Shares login session with the smartdb-cli (~/.smartdb/session.json).

If not logged in, tools will return an error asking the user to run
'smartdb login' in the CLI first.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

sys.path.insert(0, os.path.dirname(__file__))

import httpx
from mcp.server.fastmcp import FastMCP
import api_client
import variable_safety

REFERENCE_CACHE_DIR = Path.home() / ".smartdb" / "reference-cache"
FIELD_REFERENCE_FILENAME = "smartdb_field_reference.json"
DEFAULT_FIELD_REFERENCE_URL = os.environ.get(
    "SMARTDB_FIELD_REFERENCE_URL",
    "https://raw.githubusercontent.com/jnheo-md/smartdb-tools/master/"
    "reference/hospital-field-reference/smartdb_field_reference.json",
)

# ---------------------------------------------------------------------------
# MCP server instance
# ---------------------------------------------------------------------------

mcp = FastMCP(
    "SmartDB Registry",
    instructions=(
        "You have access to the SmartDB Registry database containing clinical data "
        "for ~16,000+ stroke patients across 27 Korean hospitals. The registry has ~3,000 "
        "variables covering demographics, risk factors, imaging, labs, treatment, and outcomes.\n\n"
        "VARIABLE DISCOVERY — LAYOUT-FIRST approach (MANDATORY):\n"
        "1. list_hospitals() → see available hospitals\n"
        "2. list_tables(hospital) → see tables\n"
        "3. get_layout_fields(hospital, table) → see ALL variables the hospital actually collects\n"
        "   THIS IS THE GROUND TRUTH. Different hospitals have different forms and variables.\n"
        "4. Select variables FROM the layout results for your query\n"
        "5. Run validate_variable_selection() for EVERY hospital before raw query/export\n"
        "6. query_data() or export_xlsx() only after validation passes\n"
        "NEVER query variables without first checking the layout. Hospitals customize their forms.\n\n"
        "MULTI-HOSPITAL VARIABLE SAFETY:\n"
        "- Never use YSU as the template for other hospitals. Validate each hospital independently.\n"
        "- Before exporting, confirm each requested column exists in that hospital's table layout AND has non-null data.\n"
        "- If a column exists in YSU but is missing/empty elsewhere, STOP and ask the user whether to drop it,\n"
        "  map a hospital-specific alternative, keep hospital-specific columns, or proceed with an empty column.\n"
        "- If value encoding/type/options differ between hospitals (e.g., TOAST-like fields), STOP and ask the\n"
        "  user how to normalize values and output column names before exporting.\n\n"
        "CROSS-HOSPITAL REFERENCE CACHE:\n"
        "- Use get_field_reference_status(), refresh_field_reference_cache(), lookup_field_reference(), and\n"
        "  list_field_reference_differences() when planning multi-hospital exports.\n"
        "- The cache is generated by scripts/build_hospital_field_reference.py and can be hosted on GitHub.\n"
        "- This reference helps find known differences, but live validate_variable_selection() is still required\n"
        "  before final query/export because data and layouts may have changed.\n\n"
        "For deeper exploration, you can also use:\n"
        "- get_table_variables(hospital, table) → section overview with variable counts\n"
        "- get_section_variables(hospital, table, section) → variables in a specific section\n"
        "- get_variable_info(hospital, var) → check value encoding before filtering\n"
        "- search_variables() → find which table/variable holds a specific concept\n\n"
        "NEVER guess variable names. ALWAYS show the user what sections and variables "
        "exist first, then let them choose.\n\n"
        "The main hospital is YSU (Yonsei Severance Hospital) with the richest data.\n"
        "Key tables: db_1 (Patient demographics), db_11 (Admission - main clinical data), "
        "db_12 (Thrombolysis/Treatment), db_5 (Cohort follow-up), db_19 (Stent procedures).\n\n"
        "IMPORTANT RULES:\n"
        "- For mRS outcomes, ALWAYS use get_followup_mrs() for ALL hospitals.\n"
        "  It automatically uses the cohort table (db_5) for YSU, and falls back to\n"
        "  secret_mrs_3month for other hospitals. NEVER use query_data() with\n"
        "  admission_mrs_3month or secret_mrs_3month directly.\n"
        "- For NIHSS scores, ALWAYS use get_nihss_scores() — it returns correct raw totals.\n"
        "  NEVER use NIHSS_total_day_0, NIHSS_total_day_1, NIHSS_total_dc or any NIHSS_total_*\n"
        "  CALCULATED variable — these produce false zeros via IFNULL when sub-items aren't entered.\n"
        "  Note: 'NIHSS_total' does NOT exist as a variable.\n"
        "- For filtering by date, use 'adm_date' (admission date), NOT 'onset_hospital_arrival'.\n"
        "- SELECT/CHECKBOX variables store coded values: Thr_mechanical=1 means Yes, 0 means No.\n"
        "- Use get_variable_info() to check value encoding before filtering.\n\n"
        "ANONYMIZATION:\n"
        "Some tables use anonymization — patient identity (chart number, name) is stored\n"
        "in a separate table, not in the data tables. Records use 'reg_num' instead.\n"
        "- list_anonymized_tables(hospital) → check which tables are anonymized\n"
        "- lookup_patient(hospital, query) → find a patient by chart#, name, or reg_num\n"
        "- query_data(..., include_patient_id=True) → include chart# and name in results\n"
        "- export_xlsx(..., include_patient_id=True) → create companion CSV with patient IDs\n"
        "include_patient_id works for any user with access to the hospital.\n\n"
        "RECOMMENDED WORKFLOWS:\n"
        "1. EXPLORE: list_hospitals() → list_tables() → get_layout_fields() → "
        "get_section_variables() → present variables to user → let them choose.\n"
        "2. EXPORT: explore first (above) → select variables from layout → "
        "validate_variable_selection() for every hospital → export_xlsx() or export_followup_xlsx().\n"
        "3. NIHSS: use get_nihss_scores() directly — never query NIHSS variables manually.\n"
        "4. mRS OUTCOMES: use get_followup_mrs() directly — never query mRS variables manually.\n"
        "5. PATIENT ID: use include_patient_id=True in query_data/export_xlsx, or\n"
        "   lookup_patient() for individual searches.\n"
        "Always explore before querying. Never skip the layout check."
    ),
)


# ---------------------------------------------------------------------------
# Auth check helper
# ---------------------------------------------------------------------------

def _require_auth() -> None:
    """Raise if not logged in."""
    if not api_client.is_logged_in():
        raise api_client.APIError(
            "Not logged in. Please run 'smartdb login' in the CLI first to authenticate, "
            "then restart this MCP server.",
            status_code=401,
        )


def _fetch_anon_mapping(
    hospital_code: str, hidx: int, patient_ids: list[int],
) -> tuple[dict[int, dict] | None, str | None]:
    """Fetch de-anonymized patient identifiers (chart#, name) for patient IDs.

    Uses /anon/batch which allows any logged-in user with hospital access.
    Returns (mapping_dict, error_message). mapping_dict maps
    patient_id -> {"chart_no": str, "patient_name": str}.
    """
    if not patient_ids:
        return None, None

    try:
        result = api_client.post("/anon/batch", json_body={
            "hospital": hospital_code,
            "patient_ids": [int(pid) for pid in patient_ids[:5000]],
        })
    except api_client.APIError as exc:
        if exc.status_code == 404:
            return None, None
        return None, str(exc)

    if not result:
        return None, None

    mapping: dict[int, dict] = {}
    for row in result:
        pid = row.get("patient_id")
        if pid is not None:
            mapping[int(pid)] = {
                "chart_no": str(row.get("chart_no", "")),
                "patient_name": str(row.get("patient_name", "")),
            }

    return (mapping if mapping else None), None


def _format_table(rows: list[dict], columns: list[str], max_rows: int = 50) -> str:
    """Format rows as a simple text table."""
    if not rows:
        return "(no data)"
    lines = [" | ".join(columns)]
    lines.append("-+-".join("-" * max(len(c), 8) for c in columns))
    for row in rows[:max_rows]:
        vals = [str(row.get(c, "")) for c in columns]
        lines.append(" | ".join(vals))
    if len(rows) > max_rows:
        lines.append(f"... ({len(rows) - max_rows} more rows)")
    return "\n".join(lines)


def _dedupe(items: list[str]) -> list[str]:
    """Return a list with duplicates removed while preserving order."""
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            result.append(item)
    return result


def _extract_filter_variables(filter_list: list[dict]) -> list[str]:
    """Extract variable names referenced by structured filters."""
    variables: list[str] = []
    for filt in filter_list:
        variable = filt.get("variable")
        if isinstance(variable, str) and variable:
            variables.append(variable)
    return _dedupe(variables)


def _format_dangerous_variable_block(warnings: list[dict], action: str) -> str:
    """Format a hard-stop response for known dangerous variables."""
    lines = [
        f"STOP — {action} was not run because unsafe variables were requested.",
        "",
        "Dangerous variables:",
    ]
    for warning in warnings:
        lines.append(f"  - {warning['variable']}: {warning['reason']}")
        if warning.get("safe"):
            lines.append(f"    Use '{warning['safe']}' instead, or use {warning['tool']}.")
        elif warning.get("tool"):
            lines.append(f"    Use {warning['tool']} instead.")
    lines.extend([
        "",
        "Ask the user before substituting variables or changing outcome/NIHSS handling.",
    ])
    return "\n".join(lines)


def _safe_api_error(exc: api_client.APIError) -> str:
    """Return a compact API error string for validation reports."""
    if exc.status_code:
        return f"HTTP {exc.status_code}: {exc}"
    return str(exc)


def _get_table_layout_keys(
    hospital_code: str,
    table_name: str,
    layout_cache: dict[tuple[str, str], tuple[set[str], str, str | None]],
) -> tuple[set[str], str, str | None]:
    """Return variables present in a hospital table layout.

    Prefer form_layout sections. Fall back to table-vars only when a table has
    no form layout endpoint data.
    """
    cache_key = (hospital_code, table_name)
    if cache_key in layout_cache:
        return layout_cache[cache_key]

    keys: set[str] = set()
    source = "form_layout"
    error: str | None = None

    try:
        sections = api_client.get(f"/schema/sections/{hospital_code}/{table_name}")
    except api_client.APIError as exc:
        sections = []
        error = _safe_api_error(exc)

    if sections:
        for order in sorted({section["section_order"] for section in sections}):
            try:
                section_data = api_client.get(
                    f"/schema/section-vars/{hospital_code}/{table_name}/{order}"
                )
            except api_client.APIError as exc:
                error = _safe_api_error(exc)
                continue
            for subsection in section_data.get("subsections", []):
                for variable in subsection.get("variables", []):
                    key = variable.get("key")
                    if key:
                        keys.add(key)
    else:
        source = "table_vars"
        try:
            table_vars = api_client.get(f"/schema/table-vars/{hospital_code}/{table_name}")
            for variable in table_vars:
                key = variable.get("key")
                if key:
                    keys.add(key)
            error = None
        except api_client.APIError as exc:
            error = _safe_api_error(exc)

    result = (keys, source, error)
    layout_cache[cache_key] = result
    return result


def _count_records(hospital_code: str, filters: list[dict]) -> tuple[int | None, str | None]:
    """Count records matching filters, returning an error instead of raising."""
    try:
        result = api_client.post(
            "/query/count",
            json_body={"hospital": hospital_code, "filters": filters},
        )
        return int(result.get("count", 0)), None
    except api_client.APIError as exc:
        return None, _safe_api_error(exc)


def _count_non_null_records(
    hospital_code: str,
    variable_name: str,
    filters: list[dict],
) -> tuple[int | None, str | None]:
    """Count records where a variable is non-null under the requested filters."""
    non_null_filters = list(filters) + [
        {"variable": variable_name, "operator": "IS NOT NULL"}
    ]
    return _count_records(hospital_code, non_null_filters)


def _search_variable_candidates(hospital_code: str, query: str, limit: int = 5) -> list[dict]:
    """Search variable candidates, suppressing API failures in validation."""
    try:
        result = api_client.get(
            f"/schema/search/{hospital_code}",
            params={"q": query, "limit": limit},
        )
        return result if isinstance(result, list) else []
    except api_client.APIError:
        return []


def _variable_signature(variable_info: dict) -> str:
    """Signature used to detect cross-hospital format/encoding differences."""
    value_map = variable_info.get("value_map") or {}
    normalized_value_map = {
        str(key): str(value) for key, value in sorted(value_map.items(), key=lambda item: str(item[0]))
    }
    payload = {
        "type": str(variable_info.get("type", "")),
        "type_label": str(variable_info.get("type_label", "")),
        "options": str(variable_info.get("options", "")),
        "value_map": normalized_value_map,
    }
    return json.dumps(payload, sort_keys=True, ensure_ascii=False)


def _format_variable_format(variable_info: dict) -> str:
    """Human-readable compact description of a variable's format."""
    type_label = str(variable_info.get("type_label", "") or "?")
    value_map = variable_info.get("value_map") or {}
    if value_map:
        items = [
            f"{key}={value}"
            for key, value in sorted(value_map.items(), key=lambda item: str(item[0]))[:8]
        ]
        suffix = ", ..." if len(value_map) > 8 else ""
        return f"{type_label}; values: {', '.join(items)}{suffix}"
    options = str(variable_info.get("options", "") or "").strip()
    if options:
        compact_options = " ".join(options.split())
        if len(compact_options) > 160:
            compact_options = compact_options[:157] + "..."
        return f"{type_label}; options: {compact_options}"
    return type_label


def _validate_variable_selection_impl(
    hospital_codes: list[str],
    variables: list[str],
    filter_list: list[dict],
    require_data: bool,
    search_missing: bool = True,
) -> dict:
    """Validate variable layout presence, data availability, and formats."""
    requested_variables = _dedupe(variables)
    filter_variables = _extract_filter_variables(filter_list)
    variables_to_check = _dedupe(requested_variables + filter_variables)
    layout_cache: dict[tuple[str, str], tuple[set[str], str, str | None]] = {}

    validation: dict = {
        "ok": True,
        "requires_user_decision": False,
        "hospital_codes": hospital_codes,
        "variables": requested_variables,
        "filter_variables": filter_variables,
        "require_data": require_data,
        "hospitals": [],
        "format_differences": [],
        "issues": [],
    }

    format_groups: dict[str, dict[str, list[dict]]] = {
        variable: {} for variable in requested_variables
    }

    for hospital_code in hospital_codes:
        hospital_report: dict = {
            "hospital": hospital_code,
            "total_count": None,
            "total_count_error": None,
            "variables": [],
        }

        total_count, total_error = _count_records(hospital_code, filter_list)
        hospital_report["total_count"] = total_count
        hospital_report["total_count_error"] = total_error
        if require_data and total_error:
            validation["issues"].append({
                "hospital": hospital_code,
                "variable": "(filters)",
                "severity": "BLOCK",
                "reason": f"Could not count records with current filters: {total_error}",
            })
        elif require_data and total_count == 0:
            validation["issues"].append({
                "hospital": hospital_code,
                "variable": "(filters)",
                "severity": "BLOCK",
                "reason": "No records match the current filters.",
            })

        for variable_name in variables_to_check:
            role_parts = []
            if variable_name in requested_variables:
                role_parts.append("column")
            if variable_name in filter_variables:
                role_parts.append("filter")
            variable_report: dict = {
                "name": variable_name,
                "role": "+".join(role_parts),
                "exists": False,
                "in_layout": False,
                "table": "",
                "type_label": "",
                "format": "",
                "non_null_count": None,
                "non_null_error": None,
                "suggestions": [],
                "issues": [],
            }

            try:
                variable_info = api_client.get(
                    f"/schema/variable/{hospital_code}/{variable_name}"
                )
            except api_client.APIError as exc:
                issue = f"Variable is not registered for this hospital: {_safe_api_error(exc)}"
                variable_report["issues"].append(issue)
                if search_missing:
                    variable_report["suggestions"] = _search_variable_candidates(
                        hospital_code, variable_name
                    )
                validation["issues"].append({
                    "hospital": hospital_code,
                    "variable": variable_name,
                    "severity": "BLOCK",
                    "reason": issue,
                })
                hospital_report["variables"].append(variable_report)
                continue

            variable_report["exists"] = True
            table_name = str(variable_info.get("table", "") or "")
            variable_report["table"] = table_name
            variable_report["type_label"] = str(variable_info.get("type_label", "") or "")
            variable_report["format"] = _format_variable_format(variable_info)

            layout_keys, layout_source, layout_error = _get_table_layout_keys(
                hospital_code, table_name, layout_cache
            )
            variable_report["layout_source"] = layout_source
            if layout_error and not layout_keys:
                issue = f"Could not verify table layout for {table_name}: {layout_error}"
                variable_report["issues"].append(issue)
                validation["issues"].append({
                    "hospital": hospital_code,
                    "variable": variable_name,
                    "severity": "BLOCK",
                    "reason": issue,
                })
            elif variable_name not in layout_keys:
                issue = (
                    f"Variable exists in schema table {table_name}, but is not present "
                    f"in the hospital's {layout_source} field list."
                )
                variable_report["issues"].append(issue)
                validation["issues"].append({
                    "hospital": hospital_code,
                    "variable": variable_name,
                    "severity": "BLOCK",
                    "reason": issue,
                })
            else:
                variable_report["in_layout"] = True

            if variable_name in requested_variables:
                non_null_count, non_null_error = _count_non_null_records(
                    hospital_code, variable_name, filter_list
                )
                variable_report["non_null_count"] = non_null_count
                variable_report["non_null_error"] = non_null_error
                if non_null_error:
                    issue = f"Could not verify non-null data count: {non_null_error}"
                    variable_report["issues"].append(issue)
                    validation["issues"].append({
                        "hospital": hospital_code,
                        "variable": variable_name,
                        "severity": "BLOCK" if require_data else "WARN",
                        "reason": issue,
                    })
                elif require_data and non_null_count == 0:
                    issue = "Column has 0 non-null records under the current filters."
                    variable_report["issues"].append(issue)
                    validation["issues"].append({
                        "hospital": hospital_code,
                        "variable": variable_name,
                        "severity": "BLOCK",
                        "reason": issue,
                    })

                signature = _variable_signature(variable_info)
                format_groups[variable_name].setdefault(signature, []).append({
                    "hospital": hospital_code,
                    "table": table_name,
                    "format": variable_report["format"],
                })

            hospital_report["variables"].append(variable_report)

        validation["hospitals"].append(hospital_report)

    if len(hospital_codes) > 1:
        for variable_name, groups in format_groups.items():
            if len(groups) <= 1:
                continue
            validation["format_differences"].append({
                "variable": variable_name,
                "groups": list(groups.values()),
            })
            validation["issues"].append({
                "hospital": "(multiple)",
                "variable": variable_name,
                "severity": "BLOCK",
                "reason": "Variable type/options/value encoding differ across hospitals.",
            })

    blocking_issues = [
        issue for issue in validation["issues"] if issue.get("severity") == "BLOCK"
    ]
    validation["ok"] = not blocking_issues
    validation["requires_user_decision"] = bool(blocking_issues)
    return validation


def _format_validation_report(validation: dict) -> str:
    """Format validation results for MCP users and guardrail responses."""
    lines = [
        "Variable selection preflight",
        f"Hospitals checked: {', '.join(validation['hospital_codes'])}",
        f"Requested columns: {', '.join(validation['variables']) if validation['variables'] else '(none)'}",
    ]
    if validation["filter_variables"]:
        lines.append(f"Filter variables checked: {', '.join(validation['filter_variables'])}")
    lines.append("")

    for hospital in validation["hospitals"]:
        count = hospital.get("total_count")
        count_text = "unknown" if count is None else f"{count:,}"
        if hospital.get("total_count_error"):
            count_text = f"error ({hospital['total_count_error']})"
        lines.append(f"{hospital['hospital']} — records matching filters: {count_text}")

        for variable in hospital["variables"]:
            status = "OK" if variable["exists"] and variable["in_layout"] and not variable["issues"] else "CHECK"
            data_text = ""
            if variable["role"].startswith("column") or "+column" in variable["role"]:
                non_null = variable.get("non_null_count")
                if non_null is not None:
                    data_text = f"; non-null={non_null:,}"
                elif variable.get("non_null_error"):
                    data_text = f"; non-null error={variable['non_null_error']}"
            if variable["exists"]:
                lines.append(
                    f"  [{status}] {variable['name']} ({variable['role']}): "
                    f"table={variable['table']}; layout={variable.get('layout_source', '?')}; "
                    f"{variable['format']}{data_text}"
                )
            else:
                lines.append(f"  [CHECK] {variable['name']} ({variable['role']}): missing")

            for issue in variable["issues"]:
                lines.append(f"      - {issue}")
            if variable["suggestions"]:
                suggestions = []
                for suggestion in variable["suggestions"][:5]:
                    suggestions.append(
                        f"{suggestion.get('key', '?')}[{suggestion.get('table', '?')}: "
                        f"{suggestion.get('type_label', '?')}]"
                    )
                lines.append(f"      Suggestions: {', '.join(suggestions)}")
        lines.append("")

    if validation["format_differences"]:
        lines.append("Cross-hospital format differences:")
        for difference in validation["format_differences"]:
            lines.append(f"  - {difference['variable']}:")
            for group in difference["groups"]:
                hospitals = ", ".join(item["hospital"] for item in group)
                sample = group[0]
                lines.append(
                    f"      {hospitals}: table={sample['table']}; {sample['format']}"
                )
        lines.append("")

    if validation["requires_user_decision"]:
        lines.extend([
            "STOP — user decision required before export/final column selection.",
            "Ask the user how to handle missing, empty, or differently encoded fields:",
            "  1. drop the affected hospital/column",
            "  2. map a hospital-specific alternative variable",
            "  3. normalize value encodings into a shared output column",
            "  4. keep hospital-specific columns with explicit source field names",
            "  5. proceed with empty columns only after explicit confirmation",
        ])
    elif not validation["require_data"]:
        lines.append("Preflight passed. Variables exist in each hospital layout; zero-data columns were not treated as blockers.")
    else:
        lines.append("Preflight passed. Variables exist in each hospital layout and requested columns have data.")

    return "\n".join(lines).rstrip()


def _field_reference_path() -> Path:
    return REFERENCE_CACHE_DIR / FIELD_REFERENCE_FILENAME


def _load_field_reference() -> tuple[dict | None, str | None]:
    path = _field_reference_path()
    if not path.exists():
        return None, f"No local field reference cache found at {path}."
    try:
        return json.loads(path.read_text(encoding="utf-8")), None
    except (json.JSONDecodeError, OSError) as exc:
        return None, f"Could not read field reference cache at {path}: {exc}"


def _validate_field_reference_payload(payload: dict) -> str | None:
    if not isinstance(payload, dict):
        return "Reference payload is not a JSON object."
    metadata = payload.get("metadata")
    if not isinstance(metadata, dict):
        return "Reference payload is missing metadata."
    if metadata.get("schema_version") != 1:
        return f"Unsupported reference schema_version: {metadata.get('schema_version')}"
    if not isinstance(payload.get("field_index"), dict):
        return "Reference payload is missing field_index."
    if not isinstance(payload.get("differences"), list):
        return "Reference payload is missing differences."
    return None


def _save_field_reference(payload: dict) -> Path:
    validation_error = _validate_field_reference_payload(payload)
    if validation_error:
        raise ValueError(validation_error)
    REFERENCE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = _field_reference_path()
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _download_field_reference(source_url: str) -> dict:
    parsed = urlparse(source_url)
    if parsed.scheme != "https":
        raise api_client.APIError("Field reference URL must use https.")
    if (
        parsed.netloc != "raw.githubusercontent.com"
        and os.environ.get("SMARTDB_ALLOW_CUSTOM_REFERENCE_URL") != "1"
    ):
        raise api_client.APIError(
            "Custom field reference URLs are disabled by default. "
            "Use raw.githubusercontent.com or set SMARTDB_ALLOW_CUSTOM_REFERENCE_URL=1."
        )
    with httpx.Client(timeout=60.0) as client:
        response = client.get(source_url, headers={"Accept": "application/json"})
    if response.status_code >= 400:
        raise api_client.APIError(
            f"Could not download field reference cache from {source_url} "
            f"(HTTP {response.status_code}).",
            status_code=response.status_code,
        )
    payload = response.json()
    validation_error = _validate_field_reference_payload(payload)
    if validation_error:
        raise api_client.APIError(
            f"Downloaded field reference cache is invalid: {validation_error}"
        )
    return payload


def _format_reference_metadata(payload: dict, local_path: Path | None = None) -> list[str]:
    metadata = payload.get("metadata", {})
    lines = [
        f"Schema version: {metadata.get('schema_version', '?')}",
        f"Generated at: {metadata.get('generated_at', '?')}",
        f"Privacy: {metadata.get('privacy', '?')}",
        f"Data checks: {metadata.get('data_checks', '?')}",
        f"Hospitals: {metadata.get('hospital_count', '?')}",
        f"Fields: {metadata.get('field_count', '?')}",
        f"Differences: {metadata.get('difference_count', '?')}",
    ]
    if local_path:
        lines.append(f"Local cache: {local_path}")
    if metadata.get("reference_url"):
        lines.append(f"Reference URL: {metadata['reference_url']}")
    return lines


def _matches_hospital_filter(record_hospitals: list[str], hospital_codes: list[str] | None) -> bool:
    if not hospital_codes:
        return True
    wanted = {code.upper() for code in hospital_codes}
    return bool(wanted.intersection({code.upper() for code in record_hospitals}))


# ═══════════════════════════════════════════════════════════════════════════
# Schema Tools
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def list_hospitals() -> str:
    """List all hospitals in the stroke registry system.
    Returns a formatted table of hospital codes, names, and statistics."""
    _require_auth()
    result = api_client.get("/schema/hospitals")
    lines = ["Hospitals in the Stroke Registry", ""]
    for h in result:
        lines.append(
            f"  {h['code']:5s}  hidx={h['hidx']:<3}  {h['name']:<30s}  "
            f"vars={h.get('variable_count', '?'):>5}  root={','.join(h.get('root_tables', []))}"
        )
    lines.append(f"\nTotal: {len(result)} hospital(s)")
    return "\n".join(lines)


@mcp.tool()
async def list_tables(hospital_code: str) -> str:
    """List all tables/registries for a specific hospital.
    Shows table name, purpose, number of variables, and row count.

    Args:
        hospital_code: Hospital code (e.g., 'YSU', 'EWU') or hidx number
    """
    _require_auth()
    result = api_client.get(f"/schema/tables/{hospital_code}")
    lines = [f"Tables for {hospital_code}", ""]
    for t in result:
        indent = "  " * t.get("depth", 0)
        name = t.get("table", "")
        label = t.get("label", "")
        vars_count = t.get("variable_count", 0)
        rows = t.get("row_count")
        parent = t.get("parent_table", "")
        row_str = f"rows={rows}" if rows else ""
        lines.append(f"  {indent}{name} ({label})  vars={vars_count}  {row_str}  parent={parent}")
    return "\n".join(lines)


@mcp.tool()
async def search_variables(hospital_code: str, query: str, limit: int = 20) -> str:
    """Search for a specific clinical concept across all tables.
    Use this ONLY when you need to find which table contains a particular
    variable (e.g., "where is NIHSS stored?"). For browsing what variables
    are available in a table, use get_table_variables() instead.

    Args:
        hospital_code: Hospital code (e.g., 'YSU') or hidx
        query: Search query (e.g., 'NIHSS', 'hypertension', 'blood pressure')
        limit: Max results to return (default 20)
    """
    _require_auth()
    result = api_client.get(
        f"/schema/search/{hospital_code}",
        params={"q": query, "limit": limit},
    )
    if not result:
        return f"No variables matching '{query}' found for hospital '{hospital_code}'."
    lines = [f"Search results for '{query}' in {hospital_code} ({len(result)} found)", ""]
    for i, v in enumerate(result, 1):
        lines.append(
            f"  {i:>3}. {v['key']:<35s}  table={v['table']:<8s}  "
            f"type={v.get('type_label', '?'):<12s}  label={v.get('label', '')}"
        )
    return "\n".join(lines)


@mcp.tool()
async def get_variable_info(hospital_code: str, variable_name: str) -> str:
    """Get detailed information about a specific variable/column.
    Returns key, column name, table, label, type, options, and value mapping.

    Args:
        hospital_code: Hospital code or hidx
        variable_name: Exact variable key name (e.g., 'pt_sex', 'hypertension')
    """
    _require_auth()
    result = api_client.get(f"/schema/variable/{hospital_code}/{variable_name}")
    lines = [
        f"Variable: {result['key']}  (hospital {hospital_code})",
        f"  Column:   {result.get('col', '')}",
        f"  Table:    {result.get('table', '')}",
        f"  Label:    {result.get('label', '')}",
        f"  Type:     {result.get('type_label', '')} (code {result.get('type', '')})",
    ]
    if result.get("options"):
        lines.append(f"  Options:  {result['options']}")
    if result.get("value_map"):
        lines.append("  Value Map:")
        for db_val, label in result["value_map"].items():
            lines.append(f"    {db_val} = {label}")

    type_label = result.get("type_label", "")
    if type_label == "CALCULATED" and "IFNULL" in result.get("options", ""):
        lines.append("")
        lines.append("  !! WARNING: This CALCULATED field uses IFNULL, which produces false zeros")
        lines.append("     when sub-items are not entered. Check if a raw alternative exists.")

    return "\n".join(lines)


@mcp.tool()
async def get_table_variables(hospital_code: str, table_name: str) -> str:
    """Browse variables in a table, organized by section.
    This is the PRIMARY tool for variable discovery. It shows sections
    (clinical categories) with variable counts, so the user can see
    what's available and drill into specific sections.

    Call list_tables() first to see which tables exist, then call this tool.
    Then use get_section_variables() to see variables in a specific section.

    Args:
        hospital_code: Hospital code or hidx
        table_name: Table name (e.g., 'db_1', 'db_11')
    """
    _require_auth()

    # Try sections first (form_layout-based)
    try:
        sections = api_client.get(f"/schema/sections/{hospital_code}/{table_name}")
    except api_client.APIError:
        sections = []

    if sections:
        # Group by section_order
        section_groups: dict[int, dict] = {}
        for s in sections:
            order = s["section_order"]
            if order not in section_groups:
                section_groups[order] = {
                    "title": s["section_title"],
                    "subsections": [],
                    "total_vars": 0,
                }
            section_groups[order]["subsections"].append(s)
            section_groups[order]["total_vars"] += s["variable_count"]

        total_vars = sum(g["total_vars"] for g in section_groups.values())
        lines = [
            f"Sections in {table_name} ({hospital_code}) — {len(section_groups)} sections, {total_vars} variables",
            "",
        ]
        for order in sorted(section_groups):
            g = section_groups[order]
            lines.append(f"  Section {order}. {g['title']}  ({g['total_vars']} vars)")
            for sub in g["subsections"]:
                lines.append(f"      └─ {sub['subsection_title']}  ({sub['variable_count']} vars)")

        lines.append("")
        lines.append("Use get_section_variables(hospital, table, section_number) to see the variables in a section.")
        return "\n".join(lines)

    # Fallback: flat list if no form_layout exists
    result = api_client.get(f"/schema/table-vars/{hospital_code}/{table_name}")
    if not result:
        return f"No variables found in table '{table_name}' for hospital '{hospital_code}'."
    lines = [f"Variables in {table_name} ({hospital_code}) — {len(result)} total", ""]
    for i, v in enumerate(result, 1):
        type_label = v.get('type_label', '?')
        label = v.get('label', '')
        lines.append(f"  {i:>3}. {v['key']:<35s}  [{type_label}]  {label}")
    lines.append("")
    lines.append("Use get_variable_info(hospital, variable_key) to see value encoding/options.")
    return "\n".join(lines)


@mcp.tool()
async def get_section_variables(hospital_code: str, table_name: str, section: int) -> str:
    """Show all variables in a specific section of a table.
    Use this after get_table_variables() shows the section list.
    Present these variables to the user so they can pick which ones to query.

    Args:
        hospital_code: Hospital code or hidx
        table_name: Table name (e.g., 'db_11')
        section: Section number (from get_table_variables output)
    """
    _require_auth()
    result = api_client.get(f"/schema/section-vars/{hospital_code}/{table_name}/{section}")

    section_title = result.get("section_title", f"Section {section}")
    subsections = result.get("subsections", [])

    lines = [
        f"Section {section}: {section_title}",
        f"Table: {result.get('table', table_name)} ({result.get('hospital', hospital_code)})",
        "",
    ]

    var_num = 0
    for sub in subsections:
        sub_title = sub.get("subsection_title", "")
        variables = sub.get("variables", [])
        if sub_title:
            lines.append(f"  ── {sub_title} ({len(variables)} vars) ──")
        for v in variables:
            var_num += 1
            type_label = v.get("type_label", "?")
            label = v.get("label", "")
            lines.append(f"    {var_num:>3}. {v['key']:<35s}  [{type_label}]  {label}")
        lines.append("")

    lines.append("Use get_variable_info(hospital, variable_key) to see value encoding/options for any variable.")
    return "\n".join(lines)


@mcp.tool()
async def describe_registry(hospital_code: str) -> str:
    """Get an overview of a hospital's registry structure.
    Shows the table hierarchy with variable counts, helping you decide
    which tables to browse with get_table_variables().

    Args:
        hospital_code: Hospital code or hidx
    """
    _require_auth()
    result = api_client.get(f"/schema/describe/{hospital_code}")

    summary = result.get("summary", {})
    tables = result.get("tables", [])

    lines = [
        f"Registry: {summary.get('name', hospital_code)} ({summary.get('code', hospital_code)})",
        f"Total variables: {summary.get('variable_count', '?')}",
        f"Root tables: {', '.join(summary.get('root_tables', []))}",
        "",
        "Table Hierarchy:",
    ]

    for t in tables:
        name = t.get("table", "")
        label = t.get("dbname") or ""
        vars_count = t.get("variable_count", 0)
        rows = t.get("row_count")
        parent = t.get("parent_table")
        indent = "  "
        if parent:
            indent = "    └─ "
        row_str = f"  ({rows:,} rows)" if rows else ""
        label_str = f" — {label}" if label else ""
        lines.append(f"  {indent}{name}{label_str}  [{vars_count} vars]{row_str}")

    lines.append("")
    lines.append("Use get_table_variables(hospital, table) to browse variables in any table.")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Layout & Safety Tools
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def get_layout_fields(hospital_code: str, table_name: str) -> str:
    """Get ALL variables that a hospital actually collects in their form for a table.

    THIS IS THE GROUND TRUTH for what data a hospital has. Different hospitals
    use different forms with different variables. ALWAYS check this BEFORE
    using query_data() or export_xlsx() to ensure you're querying variables
    that actually exist for this hospital.

    The result shows variables organized by form section, plus a flat list
    you can use directly in query_data().

    Args:
        hospital_code: Hospital code (e.g., 'YSU', 'EWU')
        table_name: Table name (e.g., 'db_11', 'db_29')
    """
    _require_auth()

    # Get section list from form_layout
    try:
        sections = api_client.get(f"/schema/sections/{hospital_code}/{table_name}")
    except api_client.APIError:
        sections = []

    if not sections:
        return (
            f"No form layout found for {table_name} in {hospital_code}. "
            f"This table may not exist or may not have a form layout defined. "
            f"Try list_tables({hospital_code}) to see available tables."
        )

    # Collect unique section orders
    section_orders = sorted(set(s["section_order"] for s in sections))

    all_variables: list[str] = []
    section_lines: list[str] = []

    for order in section_orders:
        try:
            result = api_client.get(
                f"/schema/section-vars/{hospital_code}/{table_name}/{order}"
            )
        except api_client.APIError:
            continue

        section_title = result.get("section_title", f"Section {order}")
        subsections = result.get("subsections", [])

        section_var_keys: list[str] = []
        for sub in subsections:
            for v in sub.get("variables", []):
                key = v["key"]
                if key not in all_variables:
                    all_variables.append(key)
                    section_var_keys.append(key)

        if section_var_keys:
            section_lines.append(
                f"  Section {order}. {section_title} ({len(section_var_keys)} vars)"
            )

    lines = [
        f"Layout fields for {table_name} ({hospital_code}) — {len(all_variables)} variables",
        "",
        "Per-section breakdown:",
    ]
    lines.extend(section_lines)
    lines.append("")
    lines.append(f"All variable keys ({len(all_variables)}):")

    # Show in chunks of 8 per line for readability
    for i in range(0, len(all_variables), 8):
        chunk = all_variables[i : i + 8]
        lines.append(f"  {', '.join(chunk)}")

    lines.append("")
    lines.append("Use these variable names in query_data() or export_xlsx().")
    return "\n".join(lines)


@mcp.tool()
async def get_field_reference_status() -> str:
    """Show status for the local cross-hospital field reference cache.

    The cache is generated by scripts/build_hospital_field_reference.py and can
    be refreshed from the GitHub raw JSON artifact.
    """
    payload, error = _load_field_reference()
    path = _field_reference_path()
    if error:
        return "\n".join([
            "Field reference cache is not available.",
            error,
            f"Default GitHub URL: {DEFAULT_FIELD_REFERENCE_URL}",
            "",
            "Generate and upload it with:",
            "  python scripts/build_hospital_field_reference.py --privacy public",
            "Then commit reference/hospital-field-reference/smartdb_field_reference.json to GitHub.",
        ])

    mtime = datetime.fromtimestamp(path.stat().st_mtime, timezone.utc).isoformat()
    lines = ["Field reference cache is available.", f"Downloaded/modified at: {mtime}"]
    lines.extend(_format_reference_metadata(payload, path))
    return "\n".join(lines)


@mcp.tool()
async def refresh_field_reference_cache(source_url: str = "", force: bool = False) -> str:
    """Download the latest cross-hospital field reference JSON cache.

    By default this reads the GitHub-hosted raw JSON generated by
    scripts/build_hospital_field_reference.py. Custom URLs are restricted to
    HTTPS raw.githubusercontent.com unless SMARTDB_ALLOW_CUSTOM_REFERENCE_URL=1.

    Args:
        source_url: Optional raw JSON URL. Defaults to the smartdb-tools GitHub URL.
        force: Accepted for compatibility; refresh always downloads the URL.
    """
    url = source_url.strip() or DEFAULT_FIELD_REFERENCE_URL
    try:
        payload = _download_field_reference(url)
        path = _save_field_reference(payload)
    except Exception as exc:
        return "\n".join([
            "Could not refresh field reference cache.",
            str(exc),
            "",
            "If the GitHub artifact does not exist yet, generate it locally:",
            "  python scripts/build_hospital_field_reference.py --privacy public",
            "Then commit and push reference/hospital-field-reference/smartdb_field_reference.json.",
        ])

    lines = ["Field reference cache refreshed.", f"Source: {url}"]
    lines.extend(_format_reference_metadata(payload, path))
    return "\n".join(lines)


@mcp.tool()
async def lookup_field_reference(
    variable_name: str,
    hospital_codes: list[str] | None = None,
    refresh_if_missing: bool = True,
) -> str:
    """Look up known cross-hospital differences for a variable.

    Use this before selecting raw export columns. This is a reference cache
    only; still run validate_variable_selection() before query_data() or
    export_xlsx() because live data/layouts may have changed.

    Args:
        variable_name: Field key to look up. Exact match preferred; substring
            matches are listed if exact match is not found.
        hospital_codes: Optional hospital filter, e.g. ['YSU', 'EWU'].
        refresh_if_missing: If True, download the GitHub cache when local cache is absent.
    """
    payload, error = _load_field_reference()
    if error and refresh_if_missing:
        try:
            payload = _download_field_reference(DEFAULT_FIELD_REFERENCE_URL)
            _save_field_reference(payload)
            error = None
        except Exception as exc:
            error = f"{error} Refresh failed: {exc}"
    if error or payload is None:
        return "\n".join([
            "Field reference cache is not available.",
            error or "",
            "Run refresh_field_reference_cache() after the GitHub artifact has been created.",
        ])

    field_index = payload.get("field_index", {})
    exact_key = variable_name if variable_name in field_index else None
    if exact_key is None:
        lower_name = variable_name.lower()
        for key in field_index:
            if key.lower() == lower_name:
                exact_key = key
                break

    if exact_key is None:
        matches = [
            key for key in sorted(field_index)
            if variable_name.lower() in key.lower()
        ][:20]
        if matches:
            return "\n".join([
                f"No exact field reference match for '{variable_name}'.",
                "Possible matches:",
                *[f"  - {match}" for match in matches],
            ])
        return f"No field reference match found for '{variable_name}'."

    entry = field_index[exact_key]
    hospital_filter = hospital_codes or []
    lines = [f"Field reference: {exact_key}"]
    lines.append(f"Generated at: {payload.get('metadata', {}).get('generated_at', '?')}")
    lines.append("")
    lines.append("Hospital fields:")

    hospitals = entry.get("hospitals", {})
    for hospital_code in sorted(hospitals):
        if hospital_filter and hospital_code.upper() not in {code.upper() for code in hospital_filter}:
            continue
        record = hospitals[hospital_code]
        value_map = record.get("value_map") or {}
        if value_map:
            values = ", ".join(
                f"{key}={value}"
                for key, value in list(value_map.items())[:8]
            )
            if len(value_map) > 8:
                values += ", ..."
        else:
            values = "(no value map)"
        lines.append(
            f"  {hospital_code}: table={record.get('table', '')}; "
            f"type={record.get('type_label', '')}; "
            f"data={record.get('non_null_records_bucket', 'unknown')}; values={values}"
        )

    differences = [
        difference for difference in entry.get("differences", [])
        if _matches_hospital_filter(
            difference.get("present_hospitals", []) + difference.get("missing_hospitals", []),
            hospital_filter,
        )
    ]
    if differences:
        lines.append("")
        lines.append("Known differences requiring review:")
        for difference in differences:
            lines.append(
                f"  - {difference.get('issue_type')}: {difference.get('summary')} "
                f"(present: {', '.join(difference.get('present_hospitals', []))}; "
                f"missing: {', '.join(difference.get('missing_hospitals', [])) or 'none'})"
            )
    else:
        lines.append("")
        lines.append("No known differences for the selected hospitals in the cached reference.")

    lines.append("")
    lines.append("Still run validate_variable_selection() before final query/export.")
    return "\n".join(lines)


@mcp.tool()
async def list_field_reference_differences(
    variable_name: str = "",
    issue_type: str = "",
    hospital_codes: list[str] | None = None,
    limit: int = 50,
    refresh_if_missing: bool = True,
) -> str:
    """List cached cross-hospital field differences.

    Args:
        variable_name: Optional exact/substring field filter.
        issue_type: Optional issue filter, e.g. missing_column,
            value_encoding_differs, data_presence_differs.
        hospital_codes: Optional hospital filter.
        limit: Max rows to return.
        refresh_if_missing: If True, download the GitHub cache when local cache is absent.
    """
    payload, error = _load_field_reference()
    if error and refresh_if_missing:
        try:
            payload = _download_field_reference(DEFAULT_FIELD_REFERENCE_URL)
            _save_field_reference(payload)
            error = None
        except Exception as exc:
            error = f"{error} Refresh failed: {exc}"
    if error or payload is None:
        return "\n".join([
            "Field reference cache is not available.",
            error or "",
            "Run refresh_field_reference_cache() after the GitHub artifact has been created.",
        ])

    lower_variable = variable_name.lower().strip()
    lower_issue = issue_type.lower().strip()
    hospital_filter = hospital_codes or []
    rows = []
    for difference in payload.get("differences", []):
        field_key = str(difference.get("field_key", ""))
        current_issue = str(difference.get("issue_type", ""))
        if lower_variable and lower_variable not in field_key.lower():
            continue
        if lower_issue and lower_issue != current_issue.lower():
            continue
        if not _matches_hospital_filter(
            difference.get("present_hospitals", []) + difference.get("missing_hospitals", []),
            hospital_filter,
        ):
            continue
        rows.append(difference)

    lines = [
        "Cached field differences",
        f"Generated at: {payload.get('metadata', {}).get('generated_at', '?')}",
        f"Matches: {len(rows)}",
        "",
    ]
    for difference in rows[: max(1, min(limit, 200))]:
        lines.append(
            f"- {difference.get('field_key')} [{difference.get('issue_type')}]: "
            f"{difference.get('summary')}"
        )
        missing = ", ".join(difference.get("missing_hospitals", []))
        if missing:
            lines.append(f"  missing: {missing}")
    if len(rows) > limit:
        lines.append(f"... ({len(rows) - limit} more)")
    lines.append("")
    lines.append("Use lookup_field_reference(variable_name) for details, then validate live before export.")
    return "\n".join(lines)


@mcp.tool()
async def validate_variable_selection(
    hospital_codes: list[str],
    variables: list[str],
    filters: str = "",
    require_data: bool = True,
) -> str:
    """Validate raw query/export variables before final column selection.

    Use this before query_data() or export_xlsx(), especially for multi-hospital
    work. It validates each hospital independently instead of assuming that
    variables present in YSU exist or are encoded the same elsewhere.

    Checks performed:
      1. Each variable/filter field is registered for each hospital.
      2. The variable exists in that hospital's table layout/field list.
      3. Requested output columns have non-null data under the current filters.
      4. Multi-hospital selections have matching type/options/value encodings.

    If anything is missing, empty, or encoded differently, stop and ask the
    user how to map/drop/normalize the affected columns before exporting.

    Args:
        hospital_codes: Hospital codes to validate (e.g., ['YSU', 'EWU'])
        variables: Requested output columns
        filters: JSON string of filters (same format as query_data)
        require_data: If True, zero non-null records is a blocking issue
    """
    _require_auth()
    if not hospital_codes:
        return "Please provide at least one hospital code to validate."
    if not variables:
        return "Please provide at least one requested output variable to validate."

    filter_list = _parse_filters(filters)
    dangerous_warnings = variable_safety.check_dangerous_variables(
        _dedupe(variables + _extract_filter_variables(filter_list)),
        "",
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "variable validation")

    validation = _validate_variable_selection_impl(
        hospital_codes=_dedupe(hospital_codes),
        variables=variables,
        filter_list=filter_list,
        require_data=require_data,
    )
    return _format_validation_report(validation)


@mcp.tool()
async def get_nihss_scores(
    hospital_code: str,
    timepoints: list[str] | None = None,
    additional_variables: list[str] | None = None,
    filters: str = "",
    limit: int = 5000,
) -> str:
    """Get NIHSS scores using the CORRECT raw variables.

    DO NOT use query_data() with NIHSS_total_* variables — those are CALCULATED
    fields that produce false zeros via IFNULL when sub-items aren't entered.

    Available timepoints: day0, day1, dc, before_evt, after_tpa
    Default: day0, day1, dc

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        timepoints: List of timepoint codes (default: ['day0', 'day1', 'dc'])
        additional_variables: Extra variables to include (e.g., ['pt_sex', 'pt_age'])
        filters: JSON string of filters (same format as query_data)
        limit: Max rows (default 5000)
    """
    _require_auth()

    timepoint_map = {
        "day0": ("admission_NIH_day_0", "NIHSS Day 0"),
        "day1": ("admission_NIH_day_1", "NIHSS Day 1"),
        "dc": ("admission_NIH_day_dc", "NIHSS at Discharge"),
        "before_evt": ("NIH_before_EVT", "NIHSS before EVT"),
        "after_tpa": ("secret_nih_after_tPA", "NIHSS after tPA"),
    }

    if timepoints is None:
        timepoints = ["day0", "day1", "dc"]

    # Validate timepoints
    invalid = [t for t in timepoints if t not in timepoint_map]
    if invalid:
        return (
            f"Invalid timepoint(s): {', '.join(invalid)}. "
            f"Available: {', '.join(timepoint_map.keys())}"
        )

    # Build variable list
    nihss_vars = []
    labels = []
    for tp in timepoints:
        var_name, label = timepoint_map[tp]
        nihss_vars.append(var_name)
        labels.append(label)

    query_vars = list(additional_variables or []) + nihss_vars

    filter_list = _parse_filters(filters)
    dangerous_warnings = variable_safety.check_dangerous_variables(
        _dedupe(query_vars + _extract_filter_variables(filter_list)),
        hospital_code,
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "NIHSS query")

    validation = _validate_variable_selection_impl(
        hospital_codes=[hospital_code],
        variables=query_vars,
        filter_list=filter_list,
        require_data=True,
    )
    if not validation["ok"]:
        return (
            _format_validation_report(validation)
            + "\n\nNIHSS query was NOT run. Confirm the correct hospital-specific NIHSS fields first."
        )

    body = {
        "hospital": hospital_code,
        "variables": query_vars,
        "filters": filter_list,
        "limit": max(1, min(limit, 5000)),
    }
    result = api_client.post("/query/data", json_body=body)

    columns = result["columns"]
    rows = result["rows"]
    summary = result.get("summary", {})

    lines = [
        f"NIHSS Scores (raw variables — correct, no false zeros)",
        f"Hospital: {result.get('hospital', hospital_code)} (hidx={result.get('hidx', '')})",
        f"Timepoints: {', '.join(labels)}",
        f"Variables used: {', '.join(nihss_vars)}",
        "Preflight: table layout and non-null data verified before query",
        f"Rows: {result['row_count']} (limit: {result['limit']})",
        "",
        _format_table(rows, columns),
    ]

    if summary:
        lines.append("\n--- NIHSS Summary ---")
        for var_name in nihss_vars:
            if var_name in summary:
                stats = summary[var_name]
                if stats.get("type") == "numeric":
                    lines.append(
                        f"  {var_name}: n={stats['n']}, mean={stats['mean']:.1f}, "
                        f"median={stats['median']:.1f}, min={stats['min']}, max={stats['max']}"
                    )
                elif stats.get("type") == "categorical":
                    lines.append(
                        f"  {var_name}: n={stats['n']}, nulls={stats['nulls']}"
                    )

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Query Tools
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def query_data(
    hospital_code: str,
    variables: list[str],
    filters: str = "",
    limit: int = 100,
    include_patient_id: bool = False,
) -> str:
    """Query patient data from the stroke registry.

    Returns tabular data for the requested variables.

    NOTE: Do NOT use this tool for mRS outcome data. Use get_followup_mrs() instead,
    which queries the authoritative cohort table (db_5) with death imputation.

    Args:
        hospital_code: Hospital code (e.g., 'YSU') or hidx
        variables: List of variable names to retrieve
                   (e.g., ['pt_sex', 'pt_age', 'hypertension'])
        filters: JSON string of filters, e.g.,
                 '[{"variable": "stroke_type", "operator": "=", "value": "LAA"}]'
                 Supported operators: =, !=, IN, NOT IN, >, <, >=, <=,
                 IS NULL, IS NOT NULL, LIKE
        limit: Max rows to return (default 100, max 5000)
        include_patient_id: If True, include original patient identifiers
                 (chart number, patient name) from the anonymization table.
                 Only works for anonymized tables and the user's own hospital.
    """
    _require_auth()
    if not variables:
        return "Please provide at least one variable to query."
    filter_list = _parse_filters(filters)

    dangerous_warnings = variable_safety.check_dangerous_variables(
        _dedupe(variables + _extract_filter_variables(filter_list)),
        hospital_code,
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "query")

    validation = _validate_variable_selection_impl(
        hospital_codes=[hospital_code],
        variables=variables,
        filter_list=filter_list,
        require_data=False,
    )
    if not validation["ok"]:
        return (
            _format_validation_report(validation)
            + "\n\nQuery was NOT run. Ask the user how to handle these fields first."
        )

    body = {
        "hospital": hospital_code,
        "variables": variables,
        "filters": filter_list,
        "limit": max(1, min(limit, 5000)),
    }
    result = api_client.post("/query/data", json_body=body)
    columns = result["columns"]
    rows = result["rows"]
    summary = result.get("summary", {})

    # De-anonymization: merge chart_no and patient_name into results
    anon_note = None
    if include_patient_id and rows:
        patient_ids = [r.get("patient_id") for r in rows if r.get("patient_id")]
        hidx = result.get("hidx")
        if patient_ids and hidx:
            anon_map, anon_err = _fetch_anon_mapping(hospital_code, hidx, patient_ids)
            if anon_err:
                anon_note = anon_err
            elif anon_map:
                columns = ["chart_no", "patient_name"] + columns
                for row in rows:
                    pid = row.get("patient_id")
                    anon = anon_map.get(int(pid)) if pid else None
                    row["chart_no"] = anon["chart_no"] if anon else ""
                    row["patient_name"] = anon["patient_name"] if anon else ""
            else:
                anon_note = "No anonymization data found (table may not be anonymized)."

    lines = []

    lines.extend([
        f"Hospital: {result.get('hospital', hospital_code)} (hidx={result.get('hidx', '')})",
        f"Variables: {', '.join(variables)}",
        "Preflight: table layout verified before query",
        f"Rows: {result['row_count']} (limit: {result['limit']})",
        "",
        _format_table(rows, columns),
    ])

    if anon_note:
        lines.append(f"\nNote: {anon_note}")

    if summary:
        lines.append("\n--- Summary ---")
        for col, stats in summary.items():
            if stats.get("type") == "numeric":
                lines.append(
                    f"  {col}: n={stats['n']}, mean={stats['mean']:.2f}, "
                    f"median={stats['median']:.2f}, min={stats['min']}, max={stats['max']}"
                )
            elif stats.get("type") == "categorical":
                top = ", ".join(f"{t['value']}={t['count']}" for t in stats.get("top", []))
                lines.append(f"  {col}: n={stats['n']}, nulls={stats['nulls']}, unique={stats['unique']}, top: {top}")

    return "\n".join(lines)


@mcp.tool()
async def get_patient_count(hospital_code: str, filters: str = "") -> str:
    """Count patients matching given criteria.

    Args:
        hospital_code: Hospital code or hidx
        filters: JSON string of filters (same format as query_data)
    """
    _require_auth()
    filter_list = _parse_filters(filters)
    body = {"hospital": hospital_code, "filters": filter_list}
    result = api_client.post("/query/count", json_body=body)
    return f"Hospital: {result['hospital']} (hidx={result.get('hidx', '')})\nPatient count: {result['count']:,}"


@mcp.tool()
async def run_sql(query: str) -> str:
    """Execute a read-only SQL query against the SmartDB database.

    SAFETY: Only SELECT queries are allowed. Any INSERT/UPDATE/DELETE/DROP/ALTER
    will be rejected. A LIMIT 1000 is auto-added if no LIMIT is present.

    Args:
        query: SQL SELECT query to execute
    """
    _require_auth()
    result = api_client.post("/query/sql", json_body={"query": query})
    columns = result["columns"]
    rows = result["rows"]
    lines = [
        f"Rows: {result['row_count']}",
        f"Columns: {', '.join(columns)}",
        "",
        _format_table(rows, columns),
    ]
    return "\n".join(lines)


@mcp.tool()
async def get_sample_data(
    hospital_code: str,
    table_name: str,
    num_rows: int = 5,
) -> str:
    """Get sample rows from a specific table to understand data format.

    Args:
        hospital_code: Hospital code or hidx
        table_name: Table name (e.g., 'db_11')
        num_rows: Number of sample rows (default 5, max 20)
    """
    _require_auth()
    body = {
        "hospital": hospital_code,
        "table": table_name,
        "rows": max(1, min(num_rows, 20)),
    }
    result = api_client.post("/query/sample", json_body=body)
    columns = result["columns"]
    rows = result["rows"]

    lines = [
        f"Hospital: {result.get('hospital', hospital_code)} | Table: {result.get('table', table_name)}",
        f"Sample rows: {len(rows)} | Total columns: {len(columns)}",
    ]

    reg_vars = result.get("registered_variables", [])
    if reg_vars:
        var_names = [v["key"] for v in reg_vars[:20]]
        lines.append(f"Registered variables ({len(reg_vars)}): {', '.join(var_names)}")
        if len(reg_vars) > 20:
            lines.append(f"  ... and {len(reg_vars) - 20} more")

    lines.append("")
    for i, row in enumerate(rows, 1):
        lines.append(f"--- Row {i} ---")
        for col in columns:
            lines.append(f"  {col}: {row.get(col)}")
        lines.append("")

    return "\n".join(lines)


@mcp.tool()
async def get_followup_mrs(
    hospital_code: str,
    period: str = "3m",
    additional_variables: list[str] | None = None,
    filters: str = "",
    limit: int = 5000,
) -> str:
    """Get mRS scores at a specific follow-up period for stroke patients.

    THIS IS THE CORRECT TOOL for mRS outcome data at ALL hospitals.
    It automatically handles hospital differences:
      - YSU: queries the cohort table (db_5, mRS_calculated) with death imputation
      - Other hospitals: falls back to secret_mrs_3month

    DO NOT use query_data() with 'admission_mrs_3month' or 'secret_mrs_3month'
    directly — use this tool instead.

    Available periods: 3m, 6m, 9m, 12m, 2y, 3y, 4y, 5y, 6y, 7y, 8y, 9y, 10y

    For date filtering, use 'adm_date' (admission date), NOT 'onset_hospital_arrival'.

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        period: Follow-up period code (default '3m')
        additional_variables: Optional list of other variables to include
                              (e.g., ['pt_sex', 'pt_age', 'Thr_mechanical'])
        filters: JSON string of filters on the patient/admission variables,
                 e.g., '[{"variable":"Thr_mechanical","operator":"=","value":"1"}]'
        limit: Max rows (default 5000)
    """
    _require_auth()
    filter_list = _parse_filters(filters)
    extra_variables = additional_variables or []
    check_variables = _dedupe(extra_variables + _extract_filter_variables(filter_list))
    dangerous_warnings = variable_safety.check_dangerous_variables(
        check_variables,
        hospital_code,
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "follow-up query")

    if check_variables:
        validation = _validate_variable_selection_impl(
            hospital_codes=[hospital_code],
            variables=extra_variables,
            filter_list=filter_list,
            require_data=False,
        )
        if not validation["ok"]:
            return (
                _format_validation_report(validation)
                + "\n\nFollow-up query was NOT run. Confirm filter/additional fields first."
            )

    body = {
        "hospital": hospital_code,
        "period": period,
        "variables": extra_variables,
        "filters": filter_list,
        "limit": max(1, min(limit, 20000)),
    }
    result = api_client.post("/query/followup", json_body=body)

    columns = result["columns"]
    rows = result["rows"]
    stats = result.get("stats", {})
    period_label = result.get("period_label", period)

    lines = [
        f"Follow-up mRS at {period_label}",
        f"Hospital: {result.get('hospital', hospital_code)}",
        f"Period: {result.get('period', period)}",
        f"Total patients: {result['row_count']}",
    ]

    if result.get("note"):
        lines.append(f"Note: {result['note']}")

    if stats:
        lines.append(f"  From cohort table: {stats.get('from_cohort', 0)}")
        imputed = stats.get("imputed_death", 0)
        if imputed:
            lines.append(f"  Imputed mRS=6 (died, no cohort row): {imputed}")

    lines.append("")
    lines.append(_format_table(rows, columns))

    if stats and stats.get("mrs_distribution"):
        lines.append(f"\n--- mRS Distribution ({period_label}) ---")
        mrs_dist = stats["mrs_distribution"]
        total = sum(mrs_dist.values())
        for score in sorted(mrs_dist.keys()):
            n = mrs_dist[score]
            pct = n / max(total, 1) * 100
            bar = "#" * int(pct / 2)
            lines.append(f"  mRS {score}: {n:>5} ({pct:5.1f}%) {bar}")
        lines.append(f"  Total: {total}")

        if stats.get("good_outcome_0_2") is not None:
            lines.append(f"  Good outcome (mRS 0-2): {stats['good_outcome_0_2']} ({stats['good_outcome_pct']:.1f}%)")
            lines.append(f"  Poor outcome (mRS 3-6): {stats['poor_outcome_3_6']} ({stats['poor_outcome_pct']:.1f}%)")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Export Tools
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def export_xlsx(
    hospital_code: str,
    variables: list[str],
    filters: str = "",
    filename: str = "",
    limit: int = 20000,
    include_patient_id: bool = False,
    allow_empty_columns: bool = False,
) -> str:
    """Export patient data to an XLSX file.

    Creates an Excel file with the requested variables as columns.
    The file is saved to the current working directory.

    For mRS outcome exports, use export_followup_xlsx() instead.

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        variables: List of variable names to include as columns
        filters: JSON string of filters (same as query_data)
        filename: Output filename (auto-generated if empty)
        limit: Max rows (default 20000)
        include_patient_id: If True, create a companion CSV with original
                 patient identifiers (chart number, name) mapped by patient_id.
                 Only works for anonymized tables and the user's own hospital.
        allow_empty_columns: If True, export can proceed after the user has
                 explicitly confirmed that zero-data columns are acceptable.
    """
    _require_auth()
    if not variables:
        return "Please provide at least one variable to export."
    filter_list = _parse_filters(filters)

    dangerous_warnings = variable_safety.check_dangerous_variables(
        _dedupe(variables + _extract_filter_variables(filter_list)),
        hospital_code,
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "export")

    validation = _validate_variable_selection_impl(
        hospital_codes=[hospital_code],
        variables=variables,
        filter_list=filter_list,
        require_data=not allow_empty_columns,
    )
    if not validation["ok"]:
        return (
            _format_validation_report(validation)
            + "\n\nExport was NOT created. Ask the user how to handle these fields first."
        )

    body = {
        "hospital": hospital_code,
        "variables": variables,
        "filters": filter_list,
        "filename": filename,
        "limit": max(1, min(limit, 50000)),
    }
    content, fname = api_client.download("/export/xlsx", json_body=body)
    fname = os.path.basename(fname)
    if not fname or fname.startswith('.'):
        fname = "download.xlsx"
    save_path = os.path.join(os.getcwd(), fname)
    with open(save_path, "wb") as f:
        f.write(content)
    size_kb = len(content) / 1024

    lines = []

    lines.extend([
        "Export complete!",
        f"  File: {save_path}",
        f"  Size: {size_kb:.1f} KB",
        f"  Hospital: {hospital_code}",
        f"  Variables: {', '.join(variables)}",
        "  Preflight: table layout and data availability verified before export",
    ])

    # Create companion mapping CSV with de-anonymized patient IDs
    if include_patient_id:
        import csv
        # Query data to get patient_ids for the same filters
        data_body = {
            "hospital": hospital_code,
            "variables": variables[:1],  # minimal query just to get patient_ids
            "filters": filter_list,
            "limit": max(1, min(limit, 50000)),
        }
        try:
            data_result = api_client.post("/query/data", json_body=data_body)
            patient_ids = [r.get("patient_id") for r in data_result.get("rows", []) if r.get("patient_id")]
            hidx = data_result.get("hidx")
            if patient_ids and hidx:
                anon_map, anon_err = _fetch_anon_mapping(hospital_code, hidx, patient_ids)
                if anon_err:
                    lines.append(f"\n  Note: {anon_err}")
                elif anon_map:
                    csv_path = save_path.rsplit(".", 1)[0] + "_patient_ids.csv"
                    with open(csv_path, "w", newline="", encoding="utf-8") as cf:
                        writer = csv.writer(cf)
                        writer.writerow(["patient_id", "chart_no", "patient_name"])
                        for pid in sorted(anon_map.keys()):
                            a = anon_map[pid]
                            writer.writerow([pid, a["chart_no"], a["patient_name"]])
                    lines.append(f"  Patient ID mapping: {csv_path}")
                    lines.append(f"  Mapped patients: {len(anon_map)}")
                else:
                    lines.append("\n  Note: No anonymization data found (table may not be anonymized).")
        except api_client.APIError:
            lines.append("\n  Note: Could not fetch patient ID mapping.")

    return "\n".join(lines)


@mcp.tool()
async def export_followup_xlsx(
    hospital_code: str,
    period: str = "3m",
    additional_variables: list[str] | None = None,
    filters: str = "",
    filename: str = "",
    limit: int = 20000,
    allow_empty_columns: bool = False,
) -> str:
    """Export mRS follow-up outcomes from the COHORT TABLE to an XLSX file.

    THIS IS THE CORRECT WAY to export patient outcomes. Uses the cohort table
    (db_5, mRS_calculated) with death imputation.

    The file is saved to the current working directory.

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        period: Follow-up period (3m, 6m, 12m, 2y, etc.)
        additional_variables: Extra variables to include (e.g., ['pt_sex', 'pt_age'])
        filters: JSON string of filters
        filename: Output filename (auto-generated if empty)
        limit: Max rows (default 20000)
        allow_empty_columns: If True, export can proceed after the user has
                 explicitly confirmed zero-data additional columns are acceptable.
    """
    _require_auth()
    filter_list = _parse_filters(filters)
    extra_variables = additional_variables or []
    check_variables = _dedupe(extra_variables + _extract_filter_variables(filter_list))
    dangerous_warnings = variable_safety.check_dangerous_variables(
        check_variables,
        hospital_code,
    )
    if dangerous_warnings:
        return _format_dangerous_variable_block(dangerous_warnings, "follow-up export")

    if check_variables:
        validation = _validate_variable_selection_impl(
            hospital_codes=[hospital_code],
            variables=extra_variables,
            filter_list=filter_list,
            require_data=not allow_empty_columns,
        )
        if not validation["ok"]:
            return (
                _format_validation_report(validation)
                + "\n\nFollow-up export was NOT created. Confirm filter/additional fields first."
            )

    body = {
        "hospital": hospital_code,
        "period": period,
        "variables": extra_variables,
        "filters": filter_list,
        "limit": max(1, min(limit, 50000)),
    }
    result = api_client.post("/query/followup", json_body=body)

    columns = result.get("columns", [])
    rows = result.get("rows", [])
    stats = result.get("stats", {})
    period_label = result.get("period_label", period)

    if not rows:
        return f"No patients found with {period_label} follow-up mRS data."

    # Write XLSX
    import csv
    import io

    if not filename:
        import datetime
        code = result.get("hospital", hospital_code)
        period_key = result.get("period", period)
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{code}_followup_mRS_{period_key}_{ts}.csv"

    # Sanitize filename to prevent path traversal
    filename = os.path.basename(filename)
    if not filename or filename.startswith('.'):
        filename = "followup_export.csv"

    # Use CSV since we don't want pandas as a dependency
    if filename.endswith(".csv"):
        save_path = os.path.join(os.getcwd(), filename)
        with open(save_path, "w", newline="", encoding="utf-8-sig") as f:
            writer = csv.DictWriter(f, fieldnames=columns)
            writer.writeheader()
            writer.writerows(rows)
    else:
        # Try xlsx via openpyxl if available
        try:
            from openpyxl import Workbook
            save_path = os.path.join(os.getcwd(), filename)
            wb = Workbook()
            ws = wb.active
            ws.append(columns)
            for row in rows:
                ws.append([row.get(c) for c in columns])
            wb.save(save_path)
        except ImportError:
            # Fallback to CSV
            filename = filename.rsplit(".", 1)[0] + ".csv"
            save_path = os.path.join(os.getcwd(), filename)
            with open(save_path, "w", newline="", encoding="utf-8-sig") as f:
                writer = csv.DictWriter(f, fieldnames=columns)
                writer.writeheader()
                writer.writerows(rows)

    size_kb = os.path.getsize(save_path) / 1024

    lines = [
        "Follow-up export complete!",
        f"  File: {save_path}",
        f"  Size: {size_kb:.1f} KB",
        f"  Hospital: {result.get('hospital', hospital_code)}",
        f"  Period: {period_label}",
        f"  Total rows: {len(rows)}",
    ]
    if check_variables:
        lines.append("  Preflight: filter/additional fields verified before export")
    if stats:
        lines.append(f"  From cohort: {stats.get('from_cohort', 0)}")
        imputed = stats.get("imputed_death", 0)
        if imputed:
            lines.append(f"  Death imputed: {imputed} (mRS=6)")

    if stats and stats.get("mrs_distribution"):
        lines.append(f"\n--- mRS Distribution ({period_label}) ---")
        mrs_dist = stats["mrs_distribution"]
        total = sum(mrs_dist.values())
        for score in sorted(mrs_dist.keys()):
            n = mrs_dist[score]
            pct = n / max(total, 1) * 100
            lines.append(f"  mRS {score}: {n:>5} ({pct:5.1f}%)")
        if stats.get("good_outcome_0_2") is not None:
            lines.append(f"  Good (mRS 0-2): {stats['good_outcome_0_2']} ({stats['good_outcome_pct']:.1f}%)")
            lines.append(f"  Poor (mRS 3-6): {stats['poor_outcome_3_6']} ({stats['poor_outcome_pct']:.1f}%)")

    return "\n".join(lines)


@mcp.tool()
async def list_exports() -> str:
    """List all previously exported XLSX files on the server."""
    _require_auth()
    result = api_client.get("/export/list")
    if not result:
        return "No exported files found on the server."
    lines = [f"Exported files ({len(result)}):", ""]
    for i, f in enumerate(result, 1):
        lines.append(f"  {i}. {f['filename']}  {f.get('size_human', '')}  {f.get('modified', '')}")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Anonymization Lookup Tools
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def list_anonymized_tables(hospital_code: str) -> str:
    """List tables that have anonymization enabled for a hospital.
    These tables store patient identity (chart number, name) in a separate
    anonymization table rather than in the data tables themselves.

    Args:
        hospital_code: Hospital code (e.g., 'KMU') or hidx number
    """
    _require_auth()
    result = api_client.get(f"/anon/tables/{hospital_code}")
    if not result:
        return f"No anonymized tables found for hospital '{hospital_code}'."
    lines = [f"Anonymized tables for {hospital_code} ({len(result)} found)", ""]
    for t in result:
        lines.append(
            f"  {t['table_name']:<10s}  dbidx={t['dbidx']:<5}  {t.get('dbname', '')}"
        )
    return "\n".join(lines)


@mcp.tool()
async def lookup_patient(
    hospital_code: str,
    query: str,
    field: str = "chart",
    table: str = "",
) -> str:
    """Look up a patient's real identity (chart number, name) from the
    anonymization table. Requires Manager or Super Admin access.

    Use this when you need to find a patient by their hospital chart number,
    name, or anonymized registry ID.

    Args:
        hospital_code: Hospital code (e.g., 'KMU') or hidx number
        query: Search value (chart number, name, or reg_num)
        field: Which field to search: 'chart' (chart number, default),
               'name' (patient name), 'id' (anonymized reg_num)
        table: Optional table filter (e.g., 'db_113') to restrict search
    """
    _require_auth()
    field_map = {"chart": "data1", "name": "data2", "id": "reg_num"}
    api_field = field_map.get(field, "data1")

    body = {
        "hospital": hospital_code,
        "query": query,
        "field": api_field,
        "table": table,
        "limit": 20,
    }
    result = api_client.post("/anon/lookup", json_body=body)

    if not result:
        return f"No matches found for '{query}' (field={field}) in hospital '{hospital_code}'."

    lines = [
        f"Anonymization lookup: '{query}' (field={field}) in {hospital_code}",
        f"Matches: {len(result)}",
        "",
    ]

    columns = ["table", "reg_num", "chart#", "name", "sex", "age"]
    lines.append(" | ".join(f"{c:<12s}" for c in columns))
    lines.append("-+-".join("-" * 12 for _ in columns))

    for r in result:
        pd = r.get("patient_data") or {}
        vals = [
            r.get("table_name", ""),
            str(r.get("reg_num", "")),
            str(r.get("data1", "")),
            str(r.get("data2", "")),
            str(pd.get("pt_sex", "")),
            str(pd.get("pt_age", "")),
        ]
        lines.append(" | ".join(f"{v:<12s}" for v in vals))

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Clot Composition Tools (ARIA)
# ═══════════════════════════════════════════════════════════════════════════


@mcp.tool()
async def get_clot_composition(hospital_code: str, thrombus_code: str) -> str:
    """Get thrombus/clot composition (stain ratios) for a specific thrombus sample.
    Shows what the blood clot retrieved during thrombectomy is made of.

    Each stain targets different components:
    - CD42b: Platelets
    - Fibrinogen: Fibrin
    - GlycophorinA: Red blood cells (RBC)
    - MPO: Neutrophils
    - TissueFactor: Tissue factor
    - HisH3: NETs (Neutrophil Extracellular Traps)
    - CD68: Macrophages
    - H&E: General histology

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        thrombus_code: Thrombus code (e.g., 'YSU001' or just '001')
    """
    _require_auth()
    result = api_client.get(f"/clot/composition/{hospital_code}/{thrombus_code}")

    if not result:
        return f"No clot composition data found for thrombus '{thrombus_code}' in hospital '{hospital_code}'."

    thrombus = result.get("thrombus_code", thrombus_code)
    patient = result.get("patient_code", "")
    stains = result.get("stains", [])

    lines = [
        f"Clot Composition — Thrombus: {thrombus}",
        f"  Patient: {patient}" if patient else "",
        "",
    ]
    lines = [l for l in lines if l or l == ""]

    if not stains:
        lines.append("  (no stain data available)")
    else:
        for s in stains:
            name = s.get("stain", "")
            ratio = s.get("ratio")
            if ratio is not None:
                lines.append(f"  {name:<20s}  {ratio}")
            else:
                lines.append(f"  {name:<20s}  (no data)")

    return "\n".join(lines)


@mcp.tool()
async def search_clot_data(hospital_code: str, query: str, field: str = "patient_code") -> str:
    """Search for thrombus/clot data by patient chart number or thrombus code.

    Args:
        hospital_code: Hospital code (e.g., 'YSU')
        query: Search value (patient chart number or thrombus code)
        field: Field to search: 'patient_code' (default) or 'thrombus_code'
    """
    _require_auth()
    body = {
        "hospital": hospital_code,
        "query": query,
        "field": field,
        "limit": 20,
    }
    result = api_client.post("/clot/search", json_body=body)

    if not result:
        return f"No clot data found for '{query}' (field={field}) in hospital '{hospital_code}'."

    lines = [
        f"Clot search: '{query}' (field={field}) in {hospital_code}",
        f"Matches: {len(result)}",
        "",
    ]

    columns = ["thrombus_code", "patient_code"]
    lines.append(_format_table(result, columns))

    return "\n".join(lines)


@mcp.tool()
async def list_clot_patients(hospital_code: str) -> str:
    """List all thrombus/clot patients for a hospital.
    Shows patients who had clot samples collected during endovascular thrombectomy.

    Args:
        hospital_code: Hospital code (e.g., 'YSU', 'KMU')
    """
    _require_auth()
    result = api_client.get(f"/clot/patients/{hospital_code}")

    if not result:
        return f"No clot patients found for hospital '{hospital_code}'."

    lines = [
        f"Clot patients for {hospital_code} ({len(result)} found)",
        "",
    ]

    columns = ["thrombus_code", "patient_code"]
    lines.append(_format_table(result, columns))

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════


def _parse_filters(filters_json: str) -> list[dict]:
    if not filters_json or not filters_json.strip():
        return []
    try:
        parsed = json.loads(filters_json)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            return [parsed]
        return []
    except (json.JSONDecodeError, TypeError):
        return []


# ═══════════════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════════════

def main():
    mcp.run()


if __name__ == "__main__":
    main()
